### ISSUE TITLE
Question about definition of normal uncertainty

### ISSUE THREAD

**Issue by johanna0626** [DavidXu-JJ/DebSDF#2]
Hi,

Thank you for your commendable efforts!

While attempting to replicate the code, I've managed to achieve credible results regarding depth uncertainty. However, I find myself perplexed by the definition of normal uncertainty. Upon reviewing the provided equations:
<img width="362" alt="屏幕截图 2024-02-26 171116" src="https://github.com/DavidXu-JJ/DebSDF/assets/79347934/ad5fb28c-b669-47fc-9140-dfdf1461dd32">
It appears that you predict normal uncertainty as a three-dimensional vector, yet after weight culmination, you calculate the average value. I'm uncertain about the rationale behind outputting a three-dimensional vector as opposed to a one-dimensional value (similar to depth uncertainty). It seems there isn't supervision for each direction as per Eq. 11. Could you please clarify whether pose rotation or other transformations are applied after predicting the normal uncertainty? Thank you in advance for your assistance.

**Comment by DavidXu-JJ** [comment]
Hi Yihao,
Thanks for your nice word.
I will reply your two questions here.

> 1) I'm uncertain about the rationale behind outputting a three-dimensional vector as opposed to a one-dimensional value (similar to depth uncertainty)

For the same piece of the region, its normal uncertainty on the x-axis may be larger than the y-axis.
In this case, the normal prediction in this region will cause a larger error in the x-axis than in the y-axis, which means normal in the x-axis is more uncertain than the y-axis.

I give an example here to help you understand what this means:
![image](https://github.com/DavidXu-JJ/DebSDF/assets/68705456/8f6b5448-e355-44d4-86b0-96468aeb5fad)

The blue arrows are correct normal prior. But the red arrow is wrong normal prior. The y-axis and z-axis uncertainty of this red arrow region may be big because it gives a wrong normal prediction.
But the normal error in the x-axis may not be so big. Suppose that the ground truth normal of the ground is (0,0,1), and the red arrow is (0,1,0). There is not so much error in the x-axis.

> 2) It seems there isn't supervision for each direction as per Eq. 11.

![image](https://github.com/DavidXu-JJ/DebSDF/assets/68705456/91a32ac6-fcdb-43e6-9c94-05155727498f)

Please ignore the Omega first for clarification. (That is just a detach operation there)

`U_n_hat`, `N_hat`, `N` are all three-dimention vectors here. So the supervision will be applied to each direction.

Hope my answer helps.

By the way, for the open source plan, this paper is currently still under review process. I will start code preparation once accepted.

Best,
Jingwei

**Comment by johanna0626** [comment]
Thank you for your detailed response. I greatly appreciate your clarification regarding the first point; it has been really helpful.

However, I still seek clarity on the matter of the loss function:

Initially, I perceived $\hat{U}_n$ as representing the mean value of normal uncertainty. Now, according to your explanation, I understand it to be a three-dimensional vector.

Considering the number of pixels as 1024, both $\hat{N}$ and $N$ have dimensions of (1024, 3). Given that you compute the L2-norm of the discrepancy between $\hat{N}$ and $N$, the shape of $||\hat{N} - N||_2$ is (1024, 1). Consequently, $\ln{\hat{U}^2_n}$ should have a shape of (1024, 3). Then we cannot calculate this.

Moreover, assuming that $\ln{\hat{U}^2_n}$ has a shape of (1024, 3), will you compute $\mathcal{L}_Mnormal$ (which should also be in shape (1024, 3)) separately in each direction, and then average or compute the norm of it?

My primary concern lies in understanding how the uncertainty is correlated with the normal in each direction after the computation of the normal's L2-norm. Any further elucidation on this matter would be greatly appreciated.

**Comment by DavidXu-JJ** [comment]
> the shape of $||\hat{N} - N||_2$ is (1024, 1)

Treating $||\hat{N} - N||_2$ as doing L2 norm per axis first, resulting (1024, 3). The following calculation may not be a big problem.

**Comment by johanna0626** [comment]
Thank you very much for your reply. Sorry for the delayed response. During this time, I have been exploring various possibilities. I am pleased to inform you that I have finally obtained a satisfactory result. Your advice has been invaluable to me.
