### ISSUE TITLE
open source 

### ISSUE THREAD

**Issue by HuTaoMylove** [DavidXu-JJ/DebSDF#3]
can;t waiting any more!

**Comment by DavidXu-JJ** [comment]
Hi,
Thanks for your interest again.
I personally also want to release the code as soon as possible.
But our current submission status is stuck after we submit our paper revision.
(The Associate Editor didn't process our revision submission for over a month. We also don't wish to be stuck here😭.)

Due to the principle of our department, we can only release the code after the paper is officially accepted.

But I think I can help you in another way. Feel free to ask about the paper details like in https://github.com/DavidXu-JJ/DebSDF/issues/2 or drop me an email. I will reply/help if I notice.

Best,
Jingwei

**Comment by DavidXu-JJ** [comment]
The code has been released. Please view the README for details.
