### ISSUE TITLE
Why need refresh_dataloader multiple times during training?

### ISSUE THREAD

**Issue by DaLi-Jack** [DavidXu-JJ/DebSDF#6]
Hi! Thanks for your great work!
I am confused that why you use refresh_dataloader multiple times during training?

**Comment by DavidXu-JJ** [comment]
Hi Junfeng,
Thanks for your question.

When we actively developed this project, I met some problems for dataloader class when we changed the members of torch dataset class. During that time I'm using an old version of torch for debugging. I even use the function like copy_() to try to solve the problem. And the problem was solved by constructing a new dataloader object.

I haven't tested whether the current newer version torch has this problem. But the refresh_dataloader() doesn't seem to break the sanity of the whole pipeline. That's why I haven't tried to remove it.

You can try to remove it if you think this is necessary for you.

**Comment by DavidXu-JJ** [comment]
BTW, I didn't notice this function would affect the running time that much.
It should be run 2 times during a whole training with the official configuration.

**Comment by DaLi-Jack** [comment]
yes, I found that the impact on running time was minimal. Thanks for your reply!
