### ISSUE TITLE
the evaluation resolution of t&t dataset

### ISSUE THREAD

**Issue by dawnzyt** [DavidXu-JJ/DebSDF#8]
Hello, thanks for opening this great work. I have a question about the evaluation resolution of t&t dataset when submitting to the t&t official website. I find that 'final_mesh_resolution' is set to 1024 in 'tnt_grids_x.conf' in your code, if this means the quantitative results on t&t datasets presented in your paper are all evaluated at 1024 resolution?
I knew that monosdf is evaluated at a resolution of 768, is debsdf consistent with monosdf?

**Comment by DavidXu-JJ** [comment]
Hi Ziyu,

Thanks for your attention to this work.

The code of this project is adapted from the resolution of t&t at MonoSDF's config:

https://github.com/autonomousvision/monosdf/blob/12513009cd20a08b35ddc2c55a7e42da2c7baf43/code/confs/tnt_grids_1.conf#L15

I'm personally not 100% sure whether the resolution in MonoSDF's config is aligned with its paper's experiment or their submitted mesh file.

But our results in the DebSDF paper are evaluated at 1024 resolution as the config mentioned above.

Since it has been a while, I may not be able to find the exact checkpoint of t&t we used for mesh evaluation.

If you're certain that MonoSDF is 768 resolution for their actual paper's evaluation, you may wish to re-run DebSDF training or MonoSDF training and extract their meshes at the same resolution you set.

Thanks for your question.

Best,
Jingwei

**Comment by DavidXu-JJ** [comment]
Feel free to reopen this issue if necessary. Or just comment under this issue.

**Comment by dawnzyt** [comment]
> Feel free to reopen this issue if necessary. Or just comment under this issue.

Ok, thank you for your reply. this helps me a lot! by the way, I learned from the monosdf issue that the resolution is set to 768:
https://github.com/autonomousvision/monosdf/issues/2#issuecomment-1184108254

**Comment by DavidXu-JJ** [comment]
Thanks for your notification! 
We may have accidentally missed this part. Sorry about that.
Thank you very much for letting us know. That also helps me a lot.
